[package]
name = "command-center-server"
version = "0.1.0"
authors = ["Banned Patriot <realbannedpatriot@protonmail.com>"]
edition = "2018"

[dependencies]
core = { path = "core" }
libloading = "0.5.2"

[workspace]
members = ["plugins/vmix", "plugins/pro-presenter", "plugins/comand-center-control", "plugins/lanbox", "plugins/onyx"]