[package]
name = "command-center-server"
version = "0.1.0"
authors = ["Banned Patriot <realbannedpatriot@protonmail.com>"]
edition = "2018"

[dependencies]
core = { path = "core" }
libloading = "0.5.2"
serde = "*"
serde_json = "*"
serde_derive = "*"

[workspace]
members = ["plugins/pro-presenter", "plugins/comand-center-control"]