[package]
name = "core"
version = "0.1.0"
authors = ["Banned Patriot <realbannedpatriot@protonmail.com"]
edition = "2018"

[dependencies]
serde = "*"
serde_json = "*"
serde_derive = "*"
tokio = { version = "1.8.1", features = ["full"] }