# Server Settings
# Use 0.0.0.0 to Bind all interfaces.
# Server Settings
server:
  ip: 0.0.0.0
  port: 2794
  
# Endpoint Settings
endpoints:
  'Pro Presenter 7':
    plugin: pro-presenter
    enabled: true
    version: 7
    ip: 127.0.0.1
    port: 4444
    password: secret
    stage_password: stage secret

  'Onyx':
    plugin: onyx
    enabled: false
    ip: 127.0.0.1
    port: 5555
          
# Plugin Settings
plugins:
  example-plugin:
    enbaled: true
  pro-presenter:
    enabled: true
  onyx:
    enabled: true
  vmix:
    enabled: true
  lanbox:
    enabled: true
